name: Build and Push Filters Registry

on:
  push:
    branches:
      - main
    paths-ignore:
      # do not trigger build on changes to the following files.
      # it is needed to avoid pull request merge blocking
      # as compiler does not use the updated config during the build.
      - 'optimization_config.json'

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: yarn install --network-concurrency 1

      - name: Lint code
        # TODO: add a separate workflow for linting
        run: yarn lint

      - name: Build filters
        run: TLS=insecure yarn build

      - name: Build patches
        # Time live of patches - '60 minutes'
        run: yarn build:patches 60 m

      - name: Validate platforms and locales
        run: yarn validate

      - name: Push to master
        run: yarn push
