name: Build Filters Registry

on:
  push:
    paths-ignore:
      # do not trigger build on changes to the following files.
      # it is needed to avoid pull request merge blocking
      # as compiler does not use the updated config during the build.
      - 'optimization_config.json'

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: yarn install
        run: yarn install --network-concurrency 1

      - name: node
        run: |
          # TODO: add a separate workflow for linting
          yarn lint

          TLS=insecure node index.js

          node validate.js
          node validate-locales.js
